<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IamZhuli.Engine\IamZhuli.Engine.csproj" />
    <ProjectReference Include="..\IamZhuli.Core\IamZhuli.Core.csproj" />
    <ProjectReference Include="..\IamZhuli.Factors\IamZhuli.Factors.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
